"""Training-only package for task router post-training workflows."""

from __future__ import annotations

from .dataset import (
    FORMAL_ENVIRONMENT_KEYS,
    ROLE_CONTROLLER,
    build_controller_sft_examples,
    load_manual_protocol_samples,
    prepare_round_assets,
    read_jsonl,
    render_controller_prompt,
    render_controller_target_text,
    sanitize_environment_payload,
    write_controller_sft_assets,
    write_jsonl,
)
from .eval import build_holdout_badcase_candidates, evaluate_holdout_predictions
from .feedback import admit_sft_admissions, annotate_teacher_queue, enqueue_teacher_queue
from .reward_specs import REWARD_SPECS
from .rounds import ROUND_ASSETS_ROOT, list_round_ids, load_round_manifest, resolve_latest_round_id
from .runtime_adapter import (
    ASSETS_ROOT,
    CONFIGS_ROOT,
    DEFAULT_CONTROLLER_STATE_VIEW,
    DOCS_ROOT,
    PACKAGE_ROOT,
    REPO_ROOT,
    build_controller_state_input,
    build_reply_state_input,
    normalize_controller_state_view,
    resolve_controller_state_view_from_config,
    validate_runtime_controller_action,
)
from .train import (
    ControllerSftJsonlDataset,
    build_grpo_rollout_groups,
    build_sft_token_labels,
    build_teacher_rankings,
    load_sft_examples,
    tokenize_sft_example,
    train_controller_grpo,
    train_controller_sft,
    validate_controller_action,
    validate_teacher_rankings,
)

__all__ = [
    "ASSETS_ROOT",
    "CONFIGS_ROOT",
    "ControllerSftJsonlDataset",
    "DEFAULT_CONTROLLER_STATE_VIEW",
    "DOCS_ROOT",
    "FORMAL_ENVIRONMENT_KEYS",
    "PACKAGE_ROOT",
    "REPO_ROOT",
    "REWARD_SPECS",
    "ROLE_CONTROLLER",
    "ROUND_ASSETS_ROOT",
    "admit_sft_admissions",
    "annotate_teacher_queue",
    "build_grpo_rollout_groups",
    "build_holdout_badcase_candidates",
    "build_controller_state_input",
    "build_controller_sft_examples",
    "build_reply_state_input",
    "build_sft_token_labels",
    "build_teacher_rankings",
    "enqueue_teacher_queue",
    "evaluate_holdout_predictions",
    "list_round_ids",
    "load_manual_protocol_samples",
    "load_round_manifest",
    "load_sft_examples",
    "normalize_controller_state_view",
    "prepare_round_assets",
    "read_jsonl",
    "render_controller_prompt",
    "render_controller_target_text",
    "resolve_controller_state_view_from_config",
    "resolve_latest_round_id",
    "sanitize_environment_payload",
    "tokenize_sft_example",
    "train_controller_grpo",
    "train_controller_sft",
    "validate_controller_action",
    "validate_runtime_controller_action",
    "validate_teacher_rankings",
    "write_controller_sft_assets",
    "write_jsonl",
]
